name: RESCUE
channels: 
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pyfastx=0.8.4
  - emu=3.4.5
  - cutadapt=4.8
  - duplex-tools=0.2.17
  - nanofilt=2.8.0
  - r-base=4.3.3
  - bioconductor-phyloseq=1.46.0
  - r-tidyverse=2.0.0